apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name  }}
  labels:
    app: {{ .Values.spec.selector.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{  .Values.spec.selector.app  }}
    app.kubernetes.io/instance: {{ .Release.Name }}


